---
- name: Déploiement projet LAMP
  hosts: all
  become: yes

  vars:
    project_git_url: "https://gitlab.com/Vincent-Antoine/trygl.git"
    web_root: "/var/www/html/trygl"
    apache_root: "{{ web_root }}/src"
    apache_conf: "/etc/httpd/conf/httpd.conf"

  tasks:
    - name: Créer utilisateur ynov
      user:
        name: ynov
        shell: /bin/bash
        create_home: yes

    - name: Installer la stack LAMP et git
      dnf:
        name:
          - httpd
          - mariadb105-server
          - php
          - php-mysqlnd
          - php-cli
          - git
        state: present
        update_cache: yes

    - name: Supprimer ancien contenu
      file:
        path: "{{ web_root }}"
        state: absent

    - name: Cloner le dépôt Git dans {{ web_root }}
      git:
        repo: "{{ project_git_url }}"
        dest: "{{ web_root }}"
        version: main
        force: yes

    - name: Télécharger et installer Composer
      block:
        - get_url:
            url: https://getcomposer.org/installer
            dest: /tmp/composer-setup.php
        - command: php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer
          args:
            creates: /usr/local/bin/composer

    - name: Installer les dépendances Composer si composer.json existe
      stat:
        path: "{{ apache_root }}/composer.json"
      register: composer_json
    - name: Run composer install
      command: /usr/local/bin/composer install --no-interaction
      args:
        chdir: "{{ apache_root }}"
      when: composer_json.stat.exists

    - name: Modifier DocumentRoot dans httpd.conf
      replace:
        path: "{{ apache_conf }}"
        regexp: '^DocumentRoot '\\".*\\"'
        replace: 'DocumentRoot "{{ apache_root }}"'

    - name: Ajouter configuration Directory pour Apache
      blockinfile:
        path: "{{ apache_conf }}"
        insertafter: '^DocumentRoot'
        block: |
          <Directory "{{ apache_root }}">
            AllowOverride None
            Require all granted
          </Directory>

    - name: Redémarrer Apache
      service:
        name: httpd
        state: restarted

    - name: Vérifier le healthcheck
      uri:
        url: http://localhost/
        status_code: 200
