---
- name: Déploiement projet LAMP
  hosts: all
  become: yes

  tasks:
    - name: Créer l’utilisateur ynov
      user:
        name: ynov
        shell: /bin/bash
        create_home: yes

    - name: Mettre à jour tous les paquets système
      dnf:
        name: "*"
        state: latest

    - name: Installer Apache
      dnf:
        name: httpd
        state: present

    - name: Installer MariaDB (Amazon Linux 2023)
      dnf:
        name: mariadb105-server
        state: present

    - name: Installer PHP et ses extensions
      dnf:
        name:
          - php
          - php-mysqlnd
          - php-cli
        state: present

    - name: Installer Git, unzip et curl
      dnf:
        name:
          - git
          - unzip
          - curl
        state: present

    - name: Démarrer et activer Apache & MariaDB
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - httpd
        - mariadb

    - name: Supprimer tout ancien contenu de l’app
      file:
        path: /var/www/html/trygl
        state: absent

    - name: Cloner le dépôt GitLab dans /var/www/html/trygl
      git:
        repo: https://gitlab.com/Vincent-Antoine/trygl.git
        dest: /var/www/html/trygl
        version: main
        force: yes
      become_user: ynov

    - name: Télécharger l’installateur Composer
      get_url:
        url: https://getcomposer.org/installer
        dest: /tmp/composer-setup.php
        mode: '0755'

    - name: Installer Composer
      command: php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer
      args:
        creates: /usr/local/bin/composer

    - name: Installer les dépendances PHP via Composer
      command: composer install --no-interaction
      args:
        chdir: /var/www/html/trygl/src

    - name: Mettre à jour le DocumentRoot pour pointer sur src
      replace:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^\s*DocumentRoot\s+'
        replace: 'DocumentRoot "/var/www/html/trygl/src"'

    - name: Autoriser l’accès au répertoire src
      blockinfile:
        path: /etc/httpd/conf/httpd.conf
        insertafter: '^DocumentRoot'
        block: |
          <Directory "/var/www/html/trygl/src">
            AllowOverride None
            Require all granted
          </Directory>

    - name: Redémarrer Apache
      service:
        name: httpd
        state: restarted

    - name: Healthcheck – s’assurer que l’app répond
      uri:
        url: http://localhost/
        status_code: 200
