---
- name: Provision EC2 LAMP application
  hosts: ec2
  become: yes

  vars:
    # Remplacez cette URL par celle de votre dépôt GitLab/GitHub
    repo_url: "https://github.com/Vincent-Antoine/tp-ansible.git"
    project_dest: "/var/www/src"

  tasks:
    - name: Create ynov user
      user:
        name: ynov
        shell: /bin/bash
        create_home: yes

    - name: Install LAMP stack and required tools
      apt:
        name:
          - apache2
          - mysql-server
          - php
          - libapache2-mod-php
          - php-mysql
          - git               # pour cloner le repo
          - php-cli           # requis par composer
          - composer          # installe Composer via apt
        state: present
        update_cache: yes

    - name: Start and enable MySQL
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Ensure Apache mod_rewrite is enabled
      apache2_module:
        name: rewrite
        state: present

    - name: Start and enable Apache
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Clone project repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ project_dest }}"
        version: HEAD
        force: yes

    - name: Ensure ynov owns the project directory
      file:
        path: "{{ project_dest }}"
        owner: ynov
        group: ynov
        recurse: yes

    - name: Install Composer dependencies
      composer:
        working_dir: "{{ project_dest }}"
        executable: composer

    - name: Configure Apache DocumentRoot
      copy:
        dest: /etc/apache2/sites-available/000-default.conf
        content: |
          <VirtualHost *:80>
            DocumentRoot {{ project_dest }}
            <Directory {{ project_dest }}>
              AllowOverride All
              Require all granted
            </Directory>
          </VirtualHost>
      notify: Reload Apache

    - name: Healthcheck (HTTP)
      uri:
        url: "http://localhost/"
        status_code: 200

  handlers:
    - name: Reload Apache
      service:
        name: apache2
        state: reloaded
