---
- name: Provision EC2 LAMP application on Amazon Linux 2023
  hosts: ec2
  become: yes

  vars:
    repo_url: "https://github.com/Vincent-Antoine/tp-ansible.git"
    project_dest: "/var/www/src"

  tasks:
    - name: Create ynov user
      user:
        name: ynov
        shell: /bin/bash
        create_home: yes

    - name: Install LAMP packages and Git via dnf
      dnf:
        name:
          - httpd
          - mariadb105-server   # installe MariaDB 10.5 server + client
          - php
          - php-mysqlnd
          - git
          - php-cli
        state: present
        update_cache: yes

    - name: Start & enable MariaDB
      service:
        name: mariadb
        state: started
        enabled: yes

    - name: Start & enable HTTPD
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Ensure project directory exists
      file:
        path: "{{ project_dest }}"
        state: directory
        owner: ynov
        group: ynov
        mode: "0755"

    - name: Clone project repository as ynov
      become_user: ynov
      git:
        repo: "{{ repo_url }}"
        dest: "{{ project_dest }}"
        version: HEAD
        force: yes

    - name: Provide default index.html if none exists
      become_user: ynov
      copy:
        dest: "{{ project_dest }}/index.html"
        content: |
          <!DOCTYPE html>
          <html>
          <head><title>It works</title></head>
          <body><h1>Application deployed successfully</h1></body>
          </html>
        owner: ynov
        group: ynov
        mode: "0644"

    - name: Disable default AWS HTTPD welcome page
      file:
        path: /etc/httpd/conf.d/welcome.conf
        state: absent

    - name: Download Composer installer
      get_url:
        url: https://getcomposer.org/installer
        dest: /tmp/composer-setup.php
      register: composer_script

    - name: Install Composer
      command: php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer
      when: composer_script.changed

    - name: Check for composer.json
      stat:
        path: "{{ project_dest }}/composer.json"
      register: composer_json

    - name: Install Composer dependencies via command
      become_user: ynov
      command: /usr/local/bin/composer install --no-interaction
      args:
        chdir: "{{ project_dest }}"
      when: composer_json.stat.exists

    - name: Skip composer install when no composer.json
      debug:
        msg: "No composer.json in {{ project_dest }}, skipping dependencies installation."
      when: not composer_json.stat.exists

    - name: Configure HTTPD DocumentRoot
      copy:
        dest: /etc/httpd/conf.d/app.conf
        content: |
          <VirtualHost *:80>
            ServerName ec2-13-39-20-169.eu-west-3.compute.amazonaws.com
            DocumentRoot {{ project_dest }}
            <Directory {{ project_dest }}>
              Options Indexes FollowSymLinks
              AllowOverride All
              Require all granted
            </Directory>
          </VirtualHost>
      notify: Restart httpd

    - name: HTTP Healthcheck
      uri:
        url: "http://127.0.0.1/"
        headers:
          Host: "{{ inventory_hostname }}"
        status_code: 200
      delegate_to: "{{ inventory_hostname }}"
      run_once: true

  handlers:
    - name: Restart httpd
      service:
        name: httpd
        state: restarted
