---
- name: Déploiement projet LAMP
  hosts: all
  become: yes

  vars:
    project_git_url: "https://gitlab.com/Vincent-Antoine/trygl.git"
    project_path: "/var/www"
    apache_conf_path: "/etc/httpd/conf/httpd.conf"
    web_root: "/var/www/html/trygl"
    apache_root: "/var/www/html/trygl"

  tasks:
    - name: Créer utilisateur ynov
      user:
        name: ynov
        state: present
        shell: /bin/bash
        create_home: yes


    - name: Installer la stack complète LAMP
      ansible.builtin.dnf:
        name:
          - httpd
          - mariadb105-server
          - php
          - php-mysqlnd
          - php-cli
          - php-json
          - php-common
          - unzip
          - git
        state: present
        update_cache: yes

    - name: Supprimer le contenu de {{ web_root }}
      ansible.builtin.file:
        path: "{{ web_root }}"
        state: absent

    - name: Cloner le dépôt Git dans {{ web_root }}
      ansible.builtin.git:
        repo: "{{ project_git_url }}"
        dest: "{{ web_root }}"
        version: main
        force: yes

    - name: Télécharger Composer
      ansible.builtin.get_url:
        url: https://getcomposer.org/installer
        dest: /tmp/composer-setup.php

    - name: Installer Composer globalement
      ansible.builtin.command:
        cmd: php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer
        creates: /usr/local/bin/composer

    - name: Modifier le DocumentRoot dans la conf Apache
      ansible.builtin.replace:
        path: "{{ apache_conf_path }}"
        regexp: '^DocumentRoot\s+".*"'
        replace: 'DocumentRoot "{{ apache_root }}"'

    - name: Ajouter configuration Directory pour Apache
      ansible.builtin.blockinfile:
        path: "{{ apache_conf_path }}"
        insertafter: "^DocumentRoot"
        block: |
          <Directory "{{ apache_root }}">
              AllowOverride None
              Require all granted
          </Directory>

    - name: Donner les droits à Apache sur {{ apache_root }}
      ansible.builtin.file:
        path: "{{ apache_root }}"
        state: directory
        recurse: yes
        owner: apache
        group: apache
        mode: "0755"

    - name: Redémarrer Apache
      ansible.builtin.service:
        name: httpd
        state: restarted

    - name: Créer un fichier index.html de test
      ansible.builtin.copy:
        dest: "{{ web_root }}/index.html"
        content: "<html><body><h1>Site OK</h1></body></html>"
        owner: apache
        group: apache
        mode: "0644"

    - name: Vérifier le healthcheck
      ansible.builtin.uri:
        url: http://localhost/
        return_content: yes
        status_code: 200
