---
- name: Provision EC2 LAMP application on Amazon Linux
  hosts: ec2
  become: yes

  vars:
    repo_url: "https://github.com/Vincent-Antoine/tp-ansible.git"
    project_dest: "/var/www/src"

  tasks:
    - name: Create ynov user
      user:
        name: ynov
        shell: /bin/bash
        create_home: yes

    - name: Install LAMP stack and required tools via yum
      yum:
        name:
          - httpd
          - mariadb-server
          - php
          - php-mysqlnd
          - git
          - php-cli
          - composer       # nécessite EPEL ou dépôt tiers
        state: present
      register: yum_install

    - name: Enable & start MariaDB
      service:
        name: mariadb
        state: started
        enabled: yes

    - name: Enable & start HTTPD
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Clone project repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ project_dest }}"
        version: HEAD
        force: yes

    - name: Chown project directory to ynov
      file:
        path: "{{ project_dest }}"
        owner: ynov
        group: ynov
        recurse: yes

    - name: Install Composer dependencies
      composer:
        working_dir: "{{ project_dest }}"
        executable: composer

    - name: Configure HTTPD DocumentRoot
      copy:
        dest: /etc/httpd/conf.d/app.conf
        content: |
          DocumentRoot {{ project_dest }}
          <Directory {{ project_dest }}>
            AllowOverride All
            Require all granted
          </Directory>
      notify: Restart httpd

    - name: HTTP Healthcheck
      uri:
        url: "http://localhost/"
        status_code: 200

  handlers:
    - name: Restart httpd
      service:
        name: httpd
        state: restarted
